### ISSUE TITLE
register not working

### ISSUE THREAD

**Issue by lordmen99** [faridelaouadi/socialNetworkApp#2]
`W/IInputConnectionWrapper(26988): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(26988): getTextAfterCursor on inactive InputConnection
I/ocialNetworkAp(26988): Background young concurrent copying GC freed 36195(1548KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 1763KB/3385KB, paused 44.951ms total 134.292ms
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist.
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:218)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.getAuth(FirebaseAuthPlugin.java:129)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:143)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/firebase_auth(26988): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/ocialNetworkAp(26988): Background young concurrent copying GC freed 39254(1554KB) AllocSpace objects, 0(0B) LOS objects, 48% free, 1733KB/3385KB, paused 523us total 109.937ms
`

**Comment by JulioEP18** [comment]
Hello, I have the same error

**Comment by JulioEP18** [comment]
Does anyone know how to fix it?
